In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import BernoulliNB
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv('/config/workspace/Dataset/diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
df.describe().T

count        mean         std     min       25%  \
Pregnancies               768.0    3.845052    3.369578   0.000   1.00000   
Glucose                   768.0  120.894531   31.972618   0.000  99.00000   
BloodPressure             768.0   69.105469   19.355807   0.000  62.00000   
SkinThickness             768.0   20.536458   15.952218   0.000   0.00000   
Insulin                   768.0   79.799479  115.244002   0.000   0.00000   
BMI                       768.0   31.992578    7.884160   0.000  27.30000   
DiabetesPedigreeFunction  768.0    0.471876    0.331329   0.078   0.24375   
Age                       768.0   33.240885   11.760232  21.000  24.00000   
Outcome                   768.0    0.348958    0.476951   0.000   0.00000   

                               50%        75%     max  
Pregnancies                 3.0000    6.00000   17.00  
Glucose                   117.0000  140.25000  199.00  
BloodPressure              72.0000   80.00000  122.00  
SkinThickness              23.0000   32.00000   99.00  
Insulin                    30.5000  127.25000  846.00  
BMI                        32.0000   36.60000   67.10  
DiabetesPedigreeFunction    0.3725    0.62625    2.42  
Age                        29.0000   41.00000   81.00  
Outcome                     0.0000    1.00000    1.00

* Outcome:-
Except Pregnacy and outcome feature other features cannot have 0 value so we need to replace it by there respective central measures.

In [4]:
df['BMI']=df['BMI'].replace(0,df['BMI'].mean())
df['Glucose']=df['Glucose'].replace(0,df['Glucose'].mean())
df['BloodPressure']=df['BloodPressure'].replace(0,df['BloodPressure'].median())
df['SkinThickness']=df['SkinThickness'].replace(0,df['SkinThickness'].median())
df['Insulin']=df['Insulin'].replace(0,df['Insulin'].median())
df['DiabetesPedigreeFunction']=df['DiabetesPedigreeFunction'].replace(0,df['DiabetesPedigreeFunction'].mean())
df['Age']=df['Age'].replace(0,df['Age'].median())

In [5]:
x=df.drop('Outcome',axis=1)
y=df['Outcome']

In [6]:
import pickle
def StandardScaler1(x_train,x_test):
    scaler=StandardScaler()
    x_train_scaled=scaler.fit_transform(x_train)
    x_test_scaled=scaler.transform(x_test)
    pickle.dump(scaler,open('/config/workspace/Dataset/Scaled.pkl','wb'))

    return x_train_scaled,x_test_scaled

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [8]:
StandardScaler1(x_train,x_test)

(array([[ 1.20267015, -0.04706038,  1.12541208, ..., -0.60094692,
         -0.65869893, -0.97190916],
        [-1.14858316, -0.24672284,  0.63170503, ...,  1.66846511,
         -0.93162844, -0.54417408],
        [-0.85467649, -0.08033746,  1.12541208, ...,  1.86955225,
          0.96997825, -0.37308004],
        ...,
        [-0.56076983, -0.745879  , -0.19114006, ..., -1.7500163 ,
         -0.72989793, -0.54417408],
        [-0.26686317, -0.18016869, -0.02657104, ..., -1.30475191,
         -0.87229594, -0.88636214],
        [ 1.20267015, -0.71260193,  0.13799798, ...,  0.97902348,
          0.53388436,  0.82457819]]),
 array([[ 0.90876348, -0.81243316,  0.302567  , ...,  1.19447399,
          1.15687563, -0.11643899],
        [-0.56076983,  0.18587916, -1.17855416, ..., -0.70149049,
          3.31954532, -0.71526811],
        [-0.85467649,  0.08604793, -1.01398514, ...,  0.46194226,
          0.09779047, -1.05745618],
        ...,
        [ 1.20267015, -0.44638531, -0.19114006, ..., -

In [9]:
# Descision Tree


parameter_tree={'criterion':['gini','entropy','log_loss'],
  'splitter':['best','random'],
  'max_depth':[1,2,3,4,5],
  'max_features':['auto', 'sqrt', 'log2']}  

grid_tree=GridSearchCV(DecisionTreeClassifier(),param_grid=parameter_tree,refit=True,cv=3,verbose=3,scoring='accuracy')
grid_tree.fit(x_train,y_train)

Fitting 3 folds for each of 90 candidates, totalling 270 fits
[CV 1/3] END criterion=gini, max_depth=1, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 2/3] END criterion=gini, max_depth=1, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 3/3] END criterion=gini, max_depth=1, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 1/3] END criterion=gini, max_depth=1, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 2/3] END criterion=gini, max_depth=1, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 3/3] END criterion=gini, max_depth=1, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 1/3] END criterion=gini, max_depth=1, max_features=sqrt, splitter=best;, score=0.651 total time=   0.0s
[CV 2/3] END criterion=gini, max_depth=1, max_features=sqrt, splitter=best;, score=0.651 total time=   0.0s
[CV 3/3] END criterion=gini, max_depth=1, max_features=sqrt, splitter=best;, sco

/config/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: 
90 fits failed out of a total of 270.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
90 fits failed with the following error:
Traceback (most recent call last):
  File "/config/.local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/config/.local/lib/python3.8/site-packages/sklearn/base.py", line 1145, in wrapper
    estimator._validate_params()
  File "/config/.local/lib/python3.8/site-packages/sklearn/base.py", line 638, in _validate_params
    validate_parameter_constraints(
  File "/config/.local/lib/python3.8/site-packages

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [1, 2, 3, 4, 5],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='accuracy', verbose=3)

In [10]:
grid_tree.best_params_

{'criterion': 'gini',
 'max_depth': 3,
 'max_features': 'log2',
 'splitter': 'best'}

In [11]:
tree_classifier=DecisionTreeClassifier(criterion= 'gini',
 max_depth= 3,
 max_features= 'log2',
 splitter= 'best')
tree_classifier.fit(x_train,y_train)
y_pred_tree=tree_classifier.predict(x_test)
print(accuracy_score(y_test,y_pred_tree))
print(confusion_matrix(y_test,y_pred_tree))
print(classification_report(y_test,y_pred_tree))

0.75
[[102  22]
 [ 26  42]]
              precision    recall  f1-score   support

           0       0.80      0.82      0.81       124
           1       0.66      0.62      0.64        68

    accuracy                           0.75       192
   macro avg       0.73      0.72      0.72       192
weighted avg       0.75      0.75      0.75       192



In [12]:
import warnings
warnings.filterwarnings('ignore')

In [14]:
# SVC
svc=SVC(C=0.1,gamma=1,kernel='linear')
svc.fit(x_train,y_train)
y_pred_svc=svc.predict(x_test)
print(accuracy_score(y_test,y_pred_svc))

0.7916666666666666


In [15]:
pickle.dump(svc,open('/config/workspace/Dataset/svc.pkl','wb'))